# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPUImageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GPUImageDemo
  pod 'GPUImage', :inhibit_warnings => true
  pod 'Masonry', :inhibit_warnings => true
  pod 'MJExtension', :inhibit_warnings => true
  pod 'CocoaLumberjack', :inhibit_warnings => true  
  target 'GPUImageDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPUImageDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
